#cloud-config
hostname: ${hostname}

users:
  - name: ${username}
    ssh_authorized_keys:
      - ${ssh_pubkey}                  # your admin key
    groups: [sudo]
    sudo: "ALL=(ALL) NOPASSWD:ALL"

ssh_pwauth: false
disable_root: true

package_update: true
package_upgrade: true
packages:
  - fail2ban
  - chrony
  - htop
  - jq
  - git
  - tmux
  - net-tools
  - unzip
  - curl
  - ufw

write_files:
  # SSH daemon hardening
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      X11Forwarding no
      AllowTcpForwarding yes
      AllowAgentForwarding no
      ClientAliveInterval 300
      ClientAliveCountMax 2
      LoginGraceTime 20

  # Persistent journald
  - path: /etc/systemd/journald.conf.d/persistent.conf
    content: |
      [Journal]
      Storage=persistent
      SystemMaxUse=1G
      MaxRetentionSec=30day

  # Fail2ban (basic SSH protection)
  - path: /etc/fail2ban/jail.d/sshd.local
    content: |
      [sshd]
      enabled = true
      bantime = 30m
      findtime = 10m
      maxretry = 5

  # DB bastion private key (PEM) — used to SSH into db-* VMs
  - path: /home/${username}/.ssh/id_ed25519_dbs
    permissions: "0600"
    content: |
      ${ssh_privkey}

  # SSH client config for convenience
  - path: /home/${username}/.ssh/config
    permissions: "0600"
    content: |
      Host db-*
        User ${username}
        IdentityFile /home/${username}/.ssh/id_ed25519_dbs
        StrictHostKeyChecking accept-new

runcmd:
  - install -d -m 700 -o ${username} -g ${username} /home/${username}/.ssh
  - chown -R ${username}:${username} /home/${username}/.ssh
  - chmod 700 /home/${username}/.ssh
  - chmod 600 /home/${username}/.ssh/*
  - systemctl restart ssh
  - systemctl enable --now chrony
  - systemctl enable --now fail2ban
  # Bastion-only firewall (do NOT do this on k8s nodes)
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw --force enable
